# Site settings
title: 꾸준히 느리게 하는 개발이야기
description: '인생은 길다. 급할거 없어.'
url: 'https://lohanyeon.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'lohanyeon'

author:
  name: 'lohanyeon'
  email: yeonkh94@gmail.com
  twitter_username: lohanyeon
  facebook_username: lohanyeon
  github_username:  lohanyeon
  linkedin_username:  lohanyeon

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
#highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  # hard_wrap: false
  syntax_highlighter: rouge

gems: ['jekyll-paginate']
# gems:
#     - jekyll-paginate-v2
#
# pagination:
#     enabled: true
#     per_page: 5
#     limit: 0
#     sort_field: "date"
#     sort_reverse: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
